name: CI

permissions:
  id-token: write
  contents: read
  packages: read

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install g++
        run: sudo apt-get update -y && sudo apt-get install g++ -y

      - name: Update CMake
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v4.0.2/cmake-4.0.2-linux-x86_64.sh
          chmod +x cmake-4.0.2-linux-x86_64.sh
          sudo ./cmake-4.0.2-linux-x86_64.sh --skip-license --prefix=/usr/local

      - name: Check CMake version
        run: cmake --version

      - name: Install stripios
        run : |
          wget https://raw.githubusercontent.com/Leseratte10/d2xl-cios/master/stripios/main.cpp
          g++ main.cpp -o stripios
          mv stripios ${DEVKITPRO}/tools/bin
          rm -f main.cpp

      - name: Configure
        run: cmake --preset ${{ matrix.build_type }}

      - name: Build
        run: cmake --build --preset ${{ matrix.build_type }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Fakemote_${{ matrix.build_type }}_${{ github.sha }}
          if-no-files-found: error
          path: |
            build/${{ matrix.build_type }}/FAKEMOTE.app